[package]
name = "zk_sql"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bls12-381 = { version = "0.4.0", default-features = false, features = [
    "curve",
] }
ark-ec = { version = "^0.4.0", default-features = false }
ark-ff = { version = "^0.4.0", default-features = false }
ark-poly = { version = "^0.4.0", default-features = false }
ark-serialize = { version = "^0.4.0", default-features = false }
ark-std = { version = "^0.4.0", default-features = false }
derivative = { version = "2", features = ["use_core"] }
displaydoc = { version = "0.2.3", default-features = false }
itertools = { version = "0.11.0", optional = true }
rand_chacha = { version = "0.3.0", default-features = false }
rayon = { version = "1.5.2", default-features = false, optional = true }
uuid = { version = "1.2", features = ["v4"] }
merlin = { version = "3.0.0", default-features = false }


[features]
default = ["parallel"]
# extensive sanity checks that are useful for debugging
extensive_sanity_checks = []
parallel = [
    "rayon",
    "itertools",
    "ark-std/parallel",
    "ark-ff/parallel",
    "ark-poly/parallel",
    "ark-ec/parallel",
]
print-trace = ["ark-std/print-trace"]
